Fix build error on windows with MSVC cl.exe with /arch:AVX2 option.
Without these intrinsic cast ops, cl.exe outputs errors like:

src/xnnpack/simd/f32-fma3.h(40): error C2440: 'function': cannot convert from 'xnn_simd_f32_t' to '__m256i'
src/xnnpack/simd/f32-fma3.h(40): error C2440: 'return': cannot convert from '__m256i' to 'xnn_simd_f32_t'
src/xnnpack/simd/f32-fma3.h(55): error C2440: 'function': cannot convert from 'xnn_simd_f32_t' to '__m256i'
src/xnnpack/simd/f32-fma3.h(55): error C2440: 'return': cannot convert from '__m256i' to 'xnn_simd_f32_t'
src/xnnpack/simd/f32-fma3.h(70): error C2440: 'function': cannot convert from 'xnn_simd_f32_t' to '__m256i'
src/xnnpack/simd/f32-fma3.h(70): error C2440: 'return': cannot convert from '__m256i' to 'xnn_simd_f32_t'

PiperOrigin-RevId: 778335801